package ru.spbstu.pipeline;

public enum RC {
    CODE_SUCCESS,
    CODE_INVALID_ARGUMENT,
    READ_ERROR,
    WRITE_ERROR,
    CODE_CONFIG_GRAMMAR_ERROR,
    INPUT_FILE_OPEN_ERROR,
    OUTPUT_FILE_OPEN_ERROR,
    BUFFER_SIZE_ERROR,
    CODE_FAILED_PIPELINE_CONSTRUCTION;
}
